# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9e52ea46629c83dd73e168a0d639203dd93d60231c972f951150b2236928b37cf7c57279485eed0fb7ebd9f23f7ab45a2226230a8eca871b57ab9c27a70e0dd

test:
  secret_key_base: 0ca2b954bbb25a54ae747f6046e686232256d4afeb45429aa82d83675ee92deab5bdef86bc4f57a346dfe9f2e40628d440cfcc0336b37839c1ad3ffc5bd5cf3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
